Traceback (most recent call last):
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olav/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/olav/.pyenv/versions/exams/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
users = get_usernames("emails.txt")
expected = ["bonnie", "clyde", "scarlett", "rhett"]
assert users == expected, f'\n{users} \n!= \n{expected}'

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m users [38;5;241m=[39m get_usernames([38;5;124m"[39m[38;5;124memails.txt[39m[38;5;124m"[39m)
[1;32m      2[0m expected [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mbonnie[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mclyde[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mscarlett[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mrhett[39m[38;5;124m"[39m]
[0;32m----> 3[0m [38;5;28;01massert[39;00m users [38;5;241m==[39m expected, [38;5;124mf[39m[38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00musers[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;130;01m\n[39;00m[38;5;124m!= [39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00mexpected[38;5;132;01m}[39;00m[38;5;124m'[39m

[0;31mAssertionError[0m: 
None 
!= 
['bonnie', 'clyde', 'scarlett', 'rhett']

