Traceback (most recent call last):
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
assert type(current_time_of_day()) == str and len(current_time_of_day()) == 8


------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [38;5;28;01massert[39;00m [38;5;28mtype[39m(current_time_of_day()) [38;5;241m==[39m [38;5;28mstr[39m [38;5;129;01mand[39;00m [38;5;28mlen[39m(current_time_of_day()) [38;5;241m==[39m [38;5;241m8[39m

[0;31mAssertionError[0m: 

